-- MySQL Script generated by MySQL Workbench
-- Thu Apr 18 16:23:48 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`Role`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Role` (
  `Role_id` INT NOT NULL,
  `name_rol` VARCHAR(45) NULL,
  `Crate_at_time` VARCHAR(45) NULL,
  `update_at_time` VARCHAR(45) NULL,
  PRIMARY KEY (`Role_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`UserUni`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`UserUni` (
  `User_id` INT NOT NULL,
  `name` VARCHAR(60) NULL,
  `email` VARCHAR(60) NULL,
  `password` VARCHAR(45) NULL,
  `Role_Role_id` INT NOT NULL,
  PRIMARY KEY (`User_id`),
  INDEX `fk_User_Role_idx` (`Role_Role_id` ASC) VISIBLE,
  CONSTRAINT `fk_User_Role`
    FOREIGN KEY (`Role_Role_id`)
    REFERENCES `mydb`.`Role` (`Role_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Uni_Carreras`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Uni_Carreras` (
  `id_carrrera` INT NOT NULL,
  `Cve_Carrera` VARCHAR(200) NULL,
  `Nombre_Carrera` VARCHAR(200) NULL,
  `Duracion` VARCHAR(45) NULL,
  `Requisitos_ad` VARCHAR(200) NULL,
  `Creditos_gradu` VARCHAR(45) NULL,
  PRIMARY KEY (`id_carrrera`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Contacto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Contacto` (
  `id_Contacto` INT NOT NULL,
  `nombre` VARCHAR(45) NULL,
  `apellido_ma` VARCHAR(45) NULL,
  `apellido_pa` VARCHAR(45) NULL,
  `Genero` VARCHAR(45) NULL,
  `email` VARCHAR(45) NULL,
  `telefono` VARCHAR(45) NULL,
  `celular` VARCHAR(45) NULL,
  `direcion` VARCHAR(45) NULL,
  `colonia` VARCHAR(45) NULL,
  `Estado` VARCHAR(45) NULL,
  `Municipio` VARCHAR(45) NULL,
  `Fecha_nacimiento` DATETIME NULL,
  `Contactocol` VARCHAR(45) NULL,
  PRIMARY KEY (`id_Contacto`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Bitacora`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Bitacora` (
  `idBitacora` INT NOT NULL,
  `Cambio_act` VARCHAR(45) NULL,
  `Cambio_anterior` VARCHAR(45) NULL,
  `Fecha_hora` VARCHAR(45) NULL,
  `User` VARCHAR(45) NULL,
  PRIMARY KEY (`idBitacora`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Uni_Profesor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Uni_Profesor` (
  `Cve_Profesor` VARCHAR(200) NOT NULL,
  `User_User_id` INT NOT NULL,
  `Contacto_id_Contacto` INT NOT NULL,
  `Especializacion` VARCHAR(45) NULL,
  `materia_impar` VARCHAR(45) NULL,
  `nivel_acade` VARCHAR(45) NULL,
  `titulo_acade` VARCHAR(45) NULL,
  `fecha_ingreso` DATE NULL,
  `Bitacora_idBitacora` INT NOT NULL,
  PRIMARY KEY (`Cve_Profesor`),
  INDEX `fk_Uni_Profesor_User1_idx` (`User_User_id` ASC) VISIBLE,
  INDEX `fk_Uni_Profesor_Contacto1_idx` (`Contacto_id_Contacto` ASC) VISIBLE,
  INDEX `fk_Uni_Profesor_Bitacora1_idx` (`Bitacora_idBitacora` ASC) VISIBLE,
  CONSTRAINT `fk_Uni_Profesor_User1`
    FOREIGN KEY (`User_User_id`)
    REFERENCES `mydb`.`UserUni` (`User_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Uni_Profesor_Contacto1`
    FOREIGN KEY (`Contacto_id_Contacto`)
    REFERENCES `mydb`.`Contacto` (`id_Contacto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Uni_Profesor_Bitacora1`
    FOREIGN KEY (`Bitacora_idBitacora`)
    REFERENCES `mydb`.`Bitacora` (`idBitacora`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Uni_Grupos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Uni_Grupos` (
  `Cve_grupo` VARCHAR(200) NOT NULL,
  `Uni_Carreras_id_carrrera` INT NOT NULL,
  `Uni_Profesor_Cve_Profesor` VARCHAR(200) NOT NULL,
  PRIMARY KEY (`Cve_grupo`),
  INDEX `fk_Uni_Grupos_Uni_Carreras1_idx` (`Uni_Carreras_id_carrrera` ASC) VISIBLE,
  INDEX `fk_Uni_Grupos_Uni_Profesor1_idx` (`Uni_Profesor_Cve_Profesor` ASC) VISIBLE,
  CONSTRAINT `fk_Uni_Grupos_Uni_Carreras1`
    FOREIGN KEY (`Uni_Carreras_id_carrrera`)
    REFERENCES `mydb`.`Uni_Carreras` (`id_carrrera`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Uni_Grupos_Uni_Profesor1`
    FOREIGN KEY (`Uni_Profesor_Cve_Profesor`)
    REFERENCES `mydb`.`Uni_Profesor` (`Cve_Profesor`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Uni_Materias`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Uni_Materias` (
  `id_materia` VARCHAR(200) NOT NULL,
  `nombre_Materia` VARCHAR(45) NULL,
  `Cred_Materia` VARCHAR(45) NULL,
  `Requisitos_Previos` VARCHAR(45) NULL,
  `Uni_Grupos_Cve_grupo` VARCHAR(200) NOT NULL,
  PRIMARY KEY (`id_materia`),
  INDEX `fk_Uni_Materias_Uni_Grupos1_idx` (`Uni_Grupos_Cve_grupo` ASC) VISIBLE,
  CONSTRAINT `fk_Uni_Materias_Uni_Grupos1`
    FOREIGN KEY (`Uni_Grupos_Cve_grupo`)
    REFERENCES `mydb`.`Uni_Grupos` (`Cve_grupo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Uni_Acreditacion_Materia`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Uni_Acreditacion_Materia` (
  `idi_Acreditacion_Mat` INT NOT NULL,
  `Tipo_de_Acreditacion` VARCHAR(45) NULL,
  `Estado_actual` VARCHAR(45) NULL,
  PRIMARY KEY (`idi_Acreditacion_Mat`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Uni_Calficacion`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Uni_Calficacion` (
  `id_calficacion` INT GENERATED ALWAYS AS () VIRTUAL,
  `fecha_evaluacion` DATE NULL,
  `Uni_Materias_id_materia` VARCHAR(200) NOT NULL,
  `Uni_Acreditacion_Materia_idi_Acreditacion_Mat` INT NOT NULL,
  PRIMARY KEY (`id_calficacion`),
  INDEX `fk_Uni_Calficacion_Uni_Materias1_idx` (`Uni_Materias_id_materia` ASC) VISIBLE,
  INDEX `fk_Uni_Calficacion_Uni_Acreditacion_Materia1_idx` (`Uni_Acreditacion_Materia_idi_Acreditacion_Mat` ASC) VISIBLE,
  CONSTRAINT `fk_Uni_Calficacion_Uni_Materias1`
    FOREIGN KEY (`Uni_Materias_id_materia`)
    REFERENCES `mydb`.`Uni_Materias` (`id_materia`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Uni_Calficacion_Uni_Acreditacion_Materia1`
    FOREIGN KEY (`Uni_Acreditacion_Materia_idi_Acreditacion_Mat`)
    REFERENCES `mydb`.`Uni_Acreditacion_Materia` (`idi_Acreditacion_Mat`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Uni_Alumnos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Uni_Alumnos` (
  `Matricula` VARCHAR(45) NOT NULL,
  `Esta_Civil` VARCHAR(45) NULL,
  `User_User_id` INT NOT NULL,
  `Contacto_id_Contacto` INT NOT NULL,
  `Uni_Calficacion_id_calficacion` INT NOT NULL,
  `Bitacora_idBitacora` INT NOT NULL,
  PRIMARY KEY (`Matricula`),
  INDEX `fk_Uni_Alumnos_User1_idx` (`User_User_id` ASC) VISIBLE,
  INDEX `fk_Uni_Alumnos_Contacto1_idx` (`Contacto_id_Contacto` ASC) VISIBLE,
  INDEX `fk_Uni_Alumnos_Uni_Calficacion1_idx` (`Uni_Calficacion_id_calficacion` ASC) VISIBLE,
  INDEX `fk_Uni_Alumnos_Bitacora1_idx` (`Bitacora_idBitacora` ASC) VISIBLE,
  CONSTRAINT `fk_Uni_Alumnos_User1`
    FOREIGN KEY (`User_User_id`)
    REFERENCES `mydb`.`UserUni` (`User_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Uni_Alumnos_Contacto1`
    FOREIGN KEY (`Contacto_id_Contacto`)
    REFERENCES `mydb`.`Contacto` (`id_Contacto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Uni_Alumnos_Uni_Calficacion1`
    FOREIGN KEY (`Uni_Calficacion_id_calficacion`)
    REFERENCES `mydb`.`Uni_Calficacion` (`id_calficacion`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Uni_Alumnos_Bitacora1`
    FOREIGN KEY (`Bitacora_idBitacora`)
    REFERENCES `mydb`.`Bitacora` (`idBitacora`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Uni_Egresados`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Uni_Egresados` (
  `Matricula` INT NOT NULL,
  `id_carrera` INT NULL,
  `año_grad` VARCHAR(45) NULL,
  `Uni_Carreras_id_carrrera` INT NOT NULL,
  PRIMARY KEY (`Matricula`),
  INDEX `fk_Uni_Egresados_Uni_Carreras1_idx` (`Uni_Carreras_id_carrrera` ASC) VISIBLE,
  CONSTRAINT `fk_Uni_Egresados_Uni_Carreras1`
    FOREIGN KEY (`Uni_Carreras_id_carrrera`)
    REFERENCES `mydb`.`Uni_Carreras` (`id_carrrera`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Uni_Kardex`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Uni_Kardex` (
  `id_kardex` INT NOT NULL,
  `Matricula` VARCHAR(200) NULL,
  `Historico` VARCHAR(45) NULL,
  `Uni_Acreditacion_Materia_idi_Acreditacion_Mat` INT NOT NULL,
  `Uni_Materias_id_materia` VARCHAR(200) NOT NULL,
  `Uni_Egresados_idUni_Egresados` INT NOT NULL,
  `Uni_Alumnos_Matricula` VARCHAR(45) NOT NULL,
  `Uni_Calficacion_id_calficacion` INT NOT NULL,
  `Bitacora_idBitacora` INT NOT NULL,
  PRIMARY KEY (`id_kardex`),
  INDEX `fk_Uni_Kardex_Uni_Acreditacion_Materia1_idx` (`Uni_Acreditacion_Materia_idi_Acreditacion_Mat` ASC) VISIBLE,
  INDEX `fk_Uni_Kardex_Uni_Materias1_idx` (`Uni_Materias_id_materia` ASC) VISIBLE,
  INDEX `fk_Uni_Kardex_Uni_Egresados1_idx` (`Uni_Egresados_idUni_Egresados` ASC) VISIBLE,
  INDEX `fk_Uni_Kardex_Uni_Alumnos1_idx` (`Uni_Alumnos_Matricula` ASC) VISIBLE,
  INDEX `fk_Uni_Kardex_Uni_Calficacion1_idx` (`Uni_Calficacion_id_calficacion` ASC) VISIBLE,
  INDEX `fk_Uni_Kardex_Bitacora1_idx` (`Bitacora_idBitacora` ASC) VISIBLE,
  CONSTRAINT `fk_Uni_Kardex_Uni_Acreditacion_Materia1`
    FOREIGN KEY (`Uni_Acreditacion_Materia_idi_Acreditacion_Mat`)
    REFERENCES `mydb`.`Uni_Acreditacion_Materia` (`idi_Acreditacion_Mat`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Uni_Kardex_Uni_Materias1`
    FOREIGN KEY (`Uni_Materias_id_materia`)
    REFERENCES `mydb`.`Uni_Materias` (`id_materia`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Uni_Kardex_Uni_Egresados1`
    FOREIGN KEY (`Uni_Egresados_idUni_Egresados`)
    REFERENCES `mydb`.`Uni_Egresados` (`Matricula`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Uni_Kardex_Uni_Alumnos1`
    FOREIGN KEY (`Uni_Alumnos_Matricula`)
    REFERENCES `mydb`.`Uni_Alumnos` (`Matricula`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Uni_Kardex_Uni_Calficacion1`
    FOREIGN KEY (`Uni_Calficacion_id_calficacion`)
    REFERENCES `mydb`.`Uni_Calficacion` (`id_calficacion`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Uni_Kardex_Bitacora1`
    FOREIGN KEY (`Bitacora_idBitacora`)
    REFERENCES `mydb`.`Bitacora` (`idBitacora`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Uni_semestre`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Uni_semestre` (
  `id_semestre` INT NOT NULL,
  `semestre` VARCHAR(45) NULL,
  `creditos` VARCHAR(45) NULL,
  `Uni_Carreras_id_carrrera` INT NOT NULL,
  PRIMARY KEY (`id_semestre`),
  INDEX `fk_Uni_semestre_Uni_Carreras1_idx` (`Uni_Carreras_id_carrrera` ASC) VISIBLE,
  CONSTRAINT `fk_Uni_semestre_Uni_Carreras1`
    FOREIGN KEY (`Uni_Carreras_id_carrrera`)
    REFERENCES `mydb`.`Uni_Carreras` (`id_carrrera`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Uni_Alumnos_has_Uni_semestre`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Uni_Alumnos_has_Uni_semestre` (
  `Uni_Alumnos_Matricula` VARCHAR(45) NOT NULL,
  `Uni_semestre_id_semestre` INT NOT NULL,
  PRIMARY KEY (`Uni_Alumnos_Matricula`, `Uni_semestre_id_semestre`),
  INDEX `fk_Uni_Alumnos_has_Uni_semestre_Uni_semestre1_idx` (`Uni_semestre_id_semestre` ASC) VISIBLE,
  INDEX `fk_Uni_Alumnos_has_Uni_semestre_Uni_Alumnos1_idx` (`Uni_Alumnos_Matricula` ASC) VISIBLE,
  CONSTRAINT `fk_Uni_Alumnos_has_Uni_semestre_Uni_Alumnos1`
    FOREIGN KEY (`Uni_Alumnos_Matricula`)
    REFERENCES `mydb`.`Uni_Alumnos` (`Matricula`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Uni_Alumnos_has_Uni_semestre_Uni_semestre1`
    FOREIGN KEY (`Uni_semestre_id_semestre`)
    REFERENCES `mydb`.`Uni_semestre` (`id_semestre`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Uni_Alumnos_has_Uni_Carreras`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Uni_Alumnos_has_Uni_Carreras` (
  `Uni_Alumnos_Matricula` VARCHAR(45) NOT NULL,
  `Uni_Carreras_id_carrrera` INT NOT NULL,
  PRIMARY KEY (`Uni_Alumnos_Matricula`, `Uni_Carreras_id_carrrera`),
  INDEX `fk_Uni_Alumnos_has_Uni_Carreras_Uni_Carreras1_idx` (`Uni_Carreras_id_carrrera` ASC) VISIBLE,
  INDEX `fk_Uni_Alumnos_has_Uni_Carreras_Uni_Alumnos1_idx` (`Uni_Alumnos_Matricula` ASC) VISIBLE,
  CONSTRAINT `fk_Uni_Alumnos_has_Uni_Carreras_Uni_Alumnos1`
    FOREIGN KEY (`Uni_Alumnos_Matricula`)
    REFERENCES `mydb`.`Uni_Alumnos` (`Matricula`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Uni_Alumnos_has_Uni_Carreras_Uni_Carreras1`
    FOREIGN KEY (`Uni_Carreras_id_carrrera`)
    REFERENCES `mydb`.`Uni_Carreras` (`id_carrrera`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
